#!/usr/bin/env python3
"""AIDSEF traceability check (playbook section 4.1.3).

Nothing in a spec is allowed to silently go untested:

  1. Every acceptance criterion in specs/<feature>/spec.md carries an
     ID (AC-001, AC-002, ...).
  2. Every test declares which IDs it covers with an annotation line
     containing 'Covers: AC-001' (comma-separate several:
     'Covers: AC-001, AC-002'). Comment syntax doesn't matter - the
     scanner matches the text in any file under tests/.
  3. This script regenerates docs/traceability/<feature>.md (the
     requirement -> test table) and exits nonzero if any criterion is
     uncovered.

Run locally (python tools/check_traceability.py) or in CI, from the
repository root. No third-party dependencies.

With --require-specs, an empty specs/*/spec.md glob is a FAILURE
instead of a pass. CI sets the flag when a pull request changes
product code (src/**) - a Feature/Fix-class change (constitution
3.1) must have a spec with AC IDs, or the gate would be a silent
no-op for exactly the changes it most needs to guard (issue #12).
Without the flag (chore PRs, fresh clones, local runs), an empty
glob still passes.

Note: criterion IDs are matched globally, so keep them unique across
features (continue numbering rather than restarting at AC-001 per
feature, or prefix: LOGIN-AC-001).
"""
import re
import sys
from pathlib import Path

SPEC_GLOB = "specs/*/spec.md"
TESTS_DIR = Path("tests")
OUT_DIR = Path("docs/traceability")

AC_DEF = re.compile(r"\b((?:[A-Z][A-Z0-9]+-)?AC-\d+)\b")
COVERS = re.compile(r"Covers:\s*((?:(?:[A-Z][A-Z0-9]+-)?AC-\d+)(?:\s*,\s*(?:(?:[A-Z][A-Z0-9]+-)?AC-\d+))*)")


def criteria_in_spec(spec_path: Path):
    """Yield (ac_id, first_line_of_criterion) in order of appearance."""
    seen = {}
    for line in spec_path.read_text(encoding="utf-8", errors="replace").splitlines():
        for ac_id in AC_DEF.findall(line):
            if ac_id not in seen:
                text = line.strip().lstrip("-*#|").strip()
                seen[ac_id] = text[:120]
    return seen


def coverage_map():
    """Map ac_id -> sorted list of test files declaring 'Covers:' it."""
    covered = {}
    if not TESTS_DIR.is_dir():
        return covered
    for path in sorted(TESTS_DIR.rglob("*")):
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for match in COVERS.finditer(text):
            for ac_id in re.split(r"\s*,\s*", match.group(1)):
                covered.setdefault(ac_id, set()).add(path.as_posix())
    return covered


def main(argv=None) -> int:
    args = sys.argv[1:] if argv is None else argv
    require_specs = "--require-specs" in args

    specs = sorted(Path(".").glob(SPEC_GLOB))
    if not specs:
        if require_specs:
            print(
                "Traceability FAILED: product code changed (Feature/Fix class) "
                "but no specs/*/spec.md exists.\n"
                "Every requirement must be phrased testably with an AC ID before "
                "product code is written (constitution core rule 2). "
                "Write the spec first - or, if this is genuinely not feature/fix "
                "work, it should not be touching src/.",
                file=sys.stderr,
            )
            return 1
        print("Traceability: no specs found - nothing to check (pass).")
        return 0

    covered = coverage_map()
    failures = []
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for spec in specs:
        feature = spec.parent.name
        criteria = criteria_in_spec(spec)
        if not criteria:
            failures.append(f"{spec.as_posix()}: no acceptance-criteria IDs (AC-###) found in spec.")
            continue

        lines = [
            f"# Traceability matrix — {feature}",
            "",
            "Generated by `tools/check_traceability.py` — do not edit by hand.",
            "Maps every acceptance criterion in the spec to the test(s) that prove it.",
            "",
            "| Criterion | Summary | Covered by |",
            "|---|---|---|",
        ]
        for ac_id, summary in criteria.items():
            tests = sorted(covered.get(ac_id, []))
            cell = "<br>".join(f"`{t}`" for t in tests) if tests else "**UNCOVERED**"
            lines.append(f"| `{ac_id}` | {summary} | {cell} |")
            if not tests:
                failures.append(f"{feature}: {ac_id} has no covering test (annotate a test with 'Covers: {ac_id}').")

        out = OUT_DIR / f"{feature}.md"
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Traceability: wrote {out.as_posix()} ({len(criteria)} criteria).")

    if failures:
        print("\nTraceability FAILED - uncovered acceptance criteria:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print("Traceability: every acceptance criterion is covered.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
